Repository UsePlease-UI/PPudding, pull requests merged in 2024-01, with the labels that each got.

#61 feat : mobile ui & code snippet 제거
  package.json
  public/robots.txt
  src/components/API/DragNDrop.tsx
  src/components/Button/Chip.tsx
  src/components/Combobox/AutoComplete.tsx
  src/components/DragNDrop/DragNDrop.tsx
  src/components/DragNDrop/DragNDropListItem.tsx
  src/components/Listbox/Select.tsx
  src/components/Menu/PopOver.tsx
  src/components/Pagination/PageList.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Tab/TabItem.tsx
  src/hooks/useMobile.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/Aside.tsx
  src/pages/Home/components/CodeSnippet.tsx
  src/pages/Home/components/Description.tsx
  src/pages/Home/components/Header.tsx
  src/pages/Home/examples/AccordionExample.tsx
  src/pages/Home/examples/AutoCompleteExample.tsx
  src/pages/Home/examples/ButtonExample.tsx
  src/pages/Home/examples/CheckboxExample.tsx
  src/pages/Home/examples/ChipExample.tsx
  src/pages/Home/examples/DragNDropExample.tsx
  src/pages/Home/examples/IconButtonExample.tsx
  src/pages/Home/examples/PaginationExample.tsx
  src/pages/Home/examples/PopOverExample.tsx
  src/pages/Home/examples/RadioExample.tsx
  src/pages/Home/examples/SelectExample.tsx
  src/pages/Home/examples/TabExample.tsx
  src/pages/Home/examples/TableExample.tsx
  src/pages/Home/examples/TextFieldExample.tsx
  src/pages/Home/examples/ToggleButtonExample.tsx
  src/pages/Home/examples/constants.ts
  src/pages/Home/examples/utils.tsx
  src/pages/Home/snippets/accordion.ts
  src/pages/Home/snippets/autoComplete.ts
  src/pages/Home/snippets/button.ts
  src/pages/Home/snippets/checkbox.ts
  src/pages/Home/snippets/chip.ts
  src/pages/Home/snippets/dragNdrop.ts
  src/pages/Home/snippets/popover.ts
  src/pages/Home/snippets/skeleton.ts
  src/stories/components/DragNDrop.stories.tsx
  yarn.lock
Labels: 버그 픽스, 데모

#67 [akffkdahffkdgo77] Listbox 컴포넌트 리팩토링
  .eslintrc.js
  src/components/Base/Backdrop/Backdrop.tsx
  src/components/Base/Box/Box.tsx
  src/components/Base/Box/index.ts
  src/components/Base/index.ts
  src/components/Button/Button/Button.tsx
  src/components/Combobox/Select/Select.tsx
  src/components/Combobox/Select/styles.ts
  src/components/Combobox/usePosition.ts
  src/components/Listbox/Listbox.tsx
  src/components/Listbox/ListboxItem.tsx
  src/components/Listbox/index.ts
  src/components/Listbox/styles.ts
  src/components/Shared/Autocomplete/Autocomplete.tsx
  src/components/Shared/Autocomplete/index.ts
  src/components/Shared/Autocomplete/styles.ts
  src/pages/Home/examples/AutoCompleteExample.tsx
  src/pages/Home/examples/constants.ts
  src/stories/components/constants.ts
Labels: 컴포넌트 수정, 데모

#68 [akffkdahffkdgo77] demo layout에 nav 추가
  src/components/Base/Backdrop/Backdrop.tsx
  src/layout/BaseLayout/BaseLayout.tsx
  src/layout/BaseLayout/components/Aside.tsx
  src/layout/BaseLayout/components/Header.tsx
  src/layout/BaseLayout/styles.ts
  src/layout/DemoLayout/DemoLayout.tsx
  src/layout/DemoLayout/styles.ts
  src/layout/components/Aside.tsx
  src/layout/components/Gnb.tsx
  src/layout/components/constants.ts
  src/layout/components/styles.ts
  src/pages/Demo/Editor/Editor.tsx
  src/pages/Demo/Editor/styles.ts
  src/pages/Demo/Register/Register.tsx
  src/pages/Demo/Register/styles.ts
  src/pages/Guide/Guide.tsx
  src/pages/Guide/styles.ts
Labels: 컴포넌트 수정

#70 mod : Guide MD 파일 내용 수정
  src/components/Accordion/Accordion.md
  src/components/Base/Base.md
  src/components/Button/Button/Button.md
  src/components/Button/Chip/Chip.md
  src/components/Button/IconButton/IconButton.md
  src/components/Button/IconButton/IconButton.tsx
  src/components/Button/IconButton/styles.ts
  src/components/Button/ToggleButton/ToggleButton.md
  src/components/Button/ToggleButton/styles.ts
  src/components/Button/styles.ts
  src/components/Combobox/Select/Select.md
  src/components/Form/Checkbox/Checkbox.md
  src/components/Form/Radio/Radio.md
  src/components/Listbox/Listbox.md
  src/components/Loader/Skeleton.md
  src/components/Tab/Tab.md
  src/components/Table/Table.md
  src/pages/Guide/Guide.tsx
  src/pages/Guide/styles.ts
  src/pages/Home/examples/ToggleButtonExample.tsx
  src/styles/reset.ts
  yarn.lock
Labels: 문서 작성

#73 [akffkdahffkdgo77] Pagination 구현
  src/components/Button/Button/Button.md
  src/components/Button/Button/Button.tsx
  src/components/Button/Button/styles.ts
  src/components/Button/IconButton/IconButton.md
  src/components/Button/IconButton/IconButton.tsx
  src/components/Button/IconButton/styles.ts
  src/components/Button/styles.ts
  src/components/Shared/Pagination/Pagination.tsx
  src/components/Shared/Pagination/index.ts
  src/components/Shared/Pagination/styles.ts
  src/pages/Home/examples/ButtonExample.tsx
  src/pages/Home/examples/PaginationExample.tsx
Labels: 컴포넌트 추가, 데모

#74 [Kimyerim1935] 캘린더
  src/components/Calender/AddSchedule.tsx
  src/components/Calender/MonthlyCalender.tsx
  src/components/Calender/WeekDays.tsx
  src/pages/Home/examples/constants.ts
Labels: 컴포넌트 추가
